using Microsoft.Extensions.Logging;

namespace BlazorMauiCssLiveReload;

public class ScopedCssCompiler
{
    private readonly ILogger<ScopedCssCompiler> _logger;
    private const int MaxRetries = 20;
    private const int RetryDelayMs = 500;

    public ScopedCssCompiler(ILogger<ScopedCssCompiler> logger)
    {
        _logger = logger;
    }

    /// <summary>
    /// Extracts actual scoped CSS from .NET compiled *.styles.css file.
    /// This ensures hash consistency with dotnet watch compilation.
    /// </summary>
    public async Task<string?> GetCompiledScopedCssAsync(string projectRoot)
    {
        try
        {
            var stylesCss = FindStylesCss(projectRoot);
            if (stylesCss == null)
            {
                _logger.LogWarning("⚠️  Compiled styles.css not found in bin folder. Make sure .NET compilation is complete.");
                return null;
            }

            // Wait for file to be fully written with increased timeout
            for (int i = 0; i < MaxRetries; i++)
            {
                try
                {
                    var css = await File.ReadAllTextAsync(stylesCss);
                    if (!string.IsNullOrWhiteSpace(css))
                    {
                        _logger.LogInformation("✓ Loaded compiled scoped CSS ({Size} bytes) on attempt {Attempt}", 
                            css.Length, i + 1);
                        return css;
                    }
                }
                catch (IOException) when (i < MaxRetries - 1)
                {
                    if (i == 0)
                    {
                        _logger.LogInformation("⏳ Waiting for .NET compilation to finish (attempt {Attempt}/{Max})...", 
                            i + 1, MaxRetries);
                    }
                    await Task.Delay(RetryDelayMs);
                }
            }

            _logger.LogWarning("⏱️  Timeout waiting for dotnet watch to compile (waited {TotalMs}ms)", 
                MaxRetries * RetryDelayMs);
            return null;
        }
        catch (Exception ex)
        {
            _logger.LogError(ex, "Error reading compiled scoped CSS.");
            return null;
        }
    }

    /// <summary>
    /// Finds the most recently compiled *.styles.css file in the bin folder.
    /// This file is generated by dotnet watch during compilation.
    /// </summary>
    public string? FindStylesCss(string projectRoot)
    {
        var bin = Path.Combine(projectRoot, "bin");
        if (!Directory.Exists(bin))
        {
            _logger.LogWarning("bin folder not found at {Path}", bin);
            return null;
        }

        var files = Directory.GetFiles(bin, "*.styles.css", SearchOption.AllDirectories);
        if (files.Length == 0)
        {
            _logger.LogWarning("No *.styles.css files found in {Path}", bin);
            return null;
        }

        // Return the most recently modified file (latest build)
        var latestFile = files.OrderByDescending(File.GetLastWriteTime).First();
        _logger.LogInformation("Found compiled styles.css: {File} (modified: {Time})",
            latestFile, File.GetLastWriteTime(latestFile));

        return latestFile;
    }
}
